# Default values for stadium-chart.
# Declare variables to be passed into your templates.

global:
  environment: dev
  namespace: stadiumapp
  registryPrefix: stadiumacr.azurecr.io

microservices:    
  stadiumapp:
    replicaCount: 2

image:
  repository: stadiumacr.azurecr.io/backend
  # Overrides the image tag whose default is the chart appVersion.
  tag: "20231220_201341_2782ebc"
  defaulttag: latest

service:
  type: ClusterIP
  port: 80
  containerPort: 3000

env:
  dev:
    SQL_HOST: database-1.cf4mjuxc3ciy.ap-northeast-1.rds.amazonaws.com
    UPLOAD_PATH: /app/static/
    DEFAULT_PROFILE_PATH: /app/default_images/
    DB: stadium
    PUBLIC_IP: 52.8.178.204

secrets:
  dev:
    JWT_KEY: LKGJBEBRJOGJTRGVORIJGEROGFJREOIGFR
    SQL_NODEJS_USER: admin
    SQL_NODEJS_PW: r11944078
    SESSION_SECRET: LKGJBEBRJOGJTRGVORIJGEROGFJREOIGFR

ingress:
  enabled: true
  annotations: {
    nginx.ingress.kubernetes.io/ssl-redirect: "false",
    nginx.ingress.kubernetes.io/rewrite-target: /$1,
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"}
  hosts:
      host: api.stadium.rdto.io
      path: /